CREATE TABLE People 
(
    Id INT NOT NULL IDENTITY PRIMARY KEY, 
    FirstName NVARCHAR(50) NOT NULL, 
    LastName NVARCHAR(50) NOT NULL
) AS NODE

CREATE TABLE Locations
(
    Id INT NOT NULL IDENTITY PRIMARY KEY,
    [Name] NVARCHAR(100) NOT NULL
) AS NODE